### ISSUE TITLE
Failed to display extracted files

### ISSUE THREAD

**Issue by Martyx00** [Vector35/blob_extractor#1]
I have tested the Blob Extractor on a random image downloaded for some old router. While the `unblob` utility manages to extract all files the plugin does not show them (even though it shows the file count).

![image](https://github.com/user-attachments/assets/7cbe1a73-3eb3-4c14-893d-20759603b4d9)
![image](https://github.com/user-attachments/assets/422f19b8-a66b-4c8c-81fc-6d301e050ba1)
[FULL_LINUX_FW.zip](https://github.com/user-attachments/files/17373376/FULL_LINUX_FW.zip)

**Comment by zznop** [comment]
Hey Marty, thanks for reporting this. I'll work to reproduce it when I have time, but I suspect that an exception occured when blob extractor was crawling the extracted squashfs directory to populate the Qt tree in the UI. Did you happen to check the log for a Python traceback?

Unfortunately sasquatch won't build for MacOS, so I didn't test squashfs extraction across very many samples (outside of some spot testing in a VM).

**Comment by zznop** [comment]
Also, did it show 1045 files right off the back when running it from Binja? Or only after you manually `cd`'d into the containing folder and ran `unblob` from the command-line?

**Comment by Martyx00** [comment]
It showed that right away. There were no messages in the Log. 
It was tested on Kali Linux basically fresh install.

**Comment by zznop** [comment]
Fixed the issue in this commit: https://github.com/Vector35/blob_extractor/commit/03e9dac1ed1d453e0605cf96aa715c04aa0bce82

Tagged 1.0.2 and prepared a new release that should be on plugin manager shortly. Thanks for reporting!
